{% set name = "blocked-matrix-utils" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a9030de0933573b0bc980d2946a28e054475733acdeb981893fda4df384c1a8a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3
    - pip
  run:
    - numpy
    - scipy
    - python >=3

test:
  imports:
    - util

about:
  home: https://github.com/vahtras/util
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: NumPy wrappers for blocked matrices

extra:
  recipe-maintainers:
    - vahtras
