{% set name = "blocked-matrix-utils" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1e4e861148e67fef70c4a0b2f838aaed21ddb976c156cd77cb8cb30b6e09c60

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3
    - pip
  run:
    - numpy
    - python >=3

test:
  imports:
    - util

about:
  home: https://github.com/vahtras/util
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: NumPy wrappers for blocked matrices

extra:
  recipe-maintainers:
    - vahtras
